### ISSUE TITLE
Fixed MY-OPEN

### ISSUE THREAD

**Issue by phoe** [bigos/qtools-testdrive#1]
```common-lisp
(defun my-open (window)
  (let ((file-name (q+::qfiledialog-get-open-file-name window "Open your first QT file" "" "*.*" ))
        (buffer (make-string 4096))
        (read 0)
        )
    (unless (equalp file-name "")
      (with-open-file (in file-name)
        (format t "file name ~S~%" file-name)
        (setf read (read-sequence buffer in))
        ;; (format t "read in ~S ~A~%" (subseq buffer 0 read) read)
        (with-slots-bound (window window)
          (q+::set-text text-edit (subseq buffer 0 read)))))))
```

**Comment by Shinmera** [comment]
1. This won't read in the full file if it's longer than the buffer.
2. Using double colons for the q+ package is bad style.
3. You can use `(setf (q+:text ..) ..)` instead of `(q+:set-text ..)` for a more native feel.
4. Why is there a dangling paren?
5. Testing for an empty string should be done with `string=`.

**Comment by phoe** [comment]
@Shinmera This is a very quick edit of @bigos 's original `my-open` function that is meant to show him how to bind `text-edit`. All of your comments are of course valid.

**Comment by bigos** [comment]
Thank you,
Using  (with-slots-bound (window window) ... ) I managed to achieve what I wanted.

**Comment by phoe** [comment]
Good - I think this is closeable then. Grab the good advice from @Shinmera and keep on asking things on Freenode in `#lisp` and `#lisp-pl` - and for Qtools, also in `#shirakumo`.

**Comment by bigos** [comment]
Yes, you can close it. But I still think it is a good idea to have a Qtools translation of the basic QT tutorial.
